version: '3'
services:
    redis:
      image: "redis:alpine"
      ports:
        - "6379:6379"
    web:
      #build: .
      image: app-test:2
      depends_on:
        - redis
      ports:
        - "5000:5000"
      